apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: book-tracker-ingress
  namespace: book-tracker
spec:
  rules:
    - host: book-tracker.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
