apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: book-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: your-dockerhub-username/book-tracker-app-web:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@db:5432/book_tracker"